---
- name: Install Docker, Docker Compose, and run the Docker image
  hosts: localhost
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt cache again after adding Docker repository
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: Install Docker Compose
      ansible.builtin.apt:
        name: docker-compose
        state: present

    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Restart Docker service
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Pull the latest version of the Docker image
      ansible.builtin.command: docker pull mohamedesmael/devops_final_project:latest
      changed_when: false  # This task doesn't modify the state if the image is already up to date

    - name: Check if the container is already running
      ansible.builtin.command: docker ps -q -f name=devops_final_project
      register: container_check
      changed_when: false  # Only checking, so no change reported

    - name: Stop the existing Docker container if it is running
      ansible.builtin.command: docker stop devops_final_project
      when: container_check.stdout != ""
      changed_when: container_check.stdout != ""  # Mark change only if container is stopped

    - name: Remove the existing Docker container if it exists
      ansible.builtin.command: docker rm devops_final_project
      when: container_check.stdout != ""
      changed_when: container_check.stdout != ""  # Mark change only if container is removed

    - name: Run the latest version of the Docker image
      ansible.builtin.command: docker run -d --name devops_final_project -p 3000:80 mohamedesmael/devops_final_project:latest
      when: container_check.stdout == ""  # Only run if the container is not already running
      changed_when: true  # This task changes the state by running the container
